Update blank.yml
teste

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -14,7 +14,30 @@ jobs:
         uses: grafana/k6-action@v0.2.0
         with: 
           filename: scripts/aula31.js  # Ajuste para o caminho correto se necessário
+      - name: Verify test file exists
+        run: |
+          if [ -f aula31.js ]; then
+            echo "Test file found: aula31.js"
+          else
+            echo "Test file not found: aula31.js"
+            exit 1
+          fi
+        shell: bash
 
+      - name: Run K6 Script with Web Dashboard and handleSummary
+        run: |
+          mkdir -p logs
+          echo "Iniciando a execução do K6 com Dashboard e Relatório HTML..."
+          # Definindo as variáveis de ambiente para o Dashboard do K6
+          export K6_WEB_DASHBOARD=true
+          export K6_WEB_DASHBOARD_EXPORT=report.html
+          # Executa o script K6 com o handleSummary e as variáveis definidas
+          k6 run --vus 2 --duration 30s --out json=output.json ./aula31.js | tee logs/k6_test.log
+          echo "Execução do K6 finalizada."
+          # Geração do segundo relatório via handleSummary
+          echo "Gerando o relatório HTML via handleSummary..."
+          k6 run --out json=output.json --summary-trend-stats "avg,p(90),p(95),max" ./VidaAP.js | tee logs/k6_test.log
+          echo "Ambos os relatórios foram gerados."
       - name: Step 3 - Create Report Directory
         run: |
           mkdir -p report
